[default.extend-words]
preconditioner = "preconditioner"
MIS = "MIS"
stoppoing = "stopping"
[default.extend-identifiers]
realy = "realy"
project2nd = "project2nd"
[default]
extend-ignore-identifiers-re = [
        "GL_.*_lod",
        "GL_.*_lod_.*",
        "GL_.*_LOD",
        "GL_.*_LOD_.*",
        "GL_.*_TESSELATION_.*",
]
[type.cpp]
extend-glob = ["*.h"]
